# Generated by Django 4.1.3 on 2022-11-21 10:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CVE', max_length=200)),
                ('severity', models.CharField(default='Severity', max_length=200)),
                ('url', models.CharField(default='URL', max_length=200)),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='platform', max_length=200), blank=True, size=None)),
                ('affected_junos', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='junos', max_length=200), blank=True, size=2), blank=True, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='tag', max_length=200), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cve', models.ManyToManyField(to='base_manager.cve')),
            ],
        ),
    ]
