# Generated by Django 4.1.3 on 2022-11-21 13:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_manager', '0002_remove_cve_id_alter_cve_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='affected_junos',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='junos', max_length=500), blank=True, size=2), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='cve',
            name='name',
            field=models.CharField(default='CVE', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cve',
            name='platforms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='platform', max_length=500), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='cve',
            name='severity',
            field=models.CharField(default='Severity', max_length=500),
        ),
        migrations.AlterField(
            model_name='cve',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='tag', max_length=500), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='cve',
            name='url',
            field=models.CharField(default='URL', max_length=500),
        ),
    ]
